//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
// 
namespace CSharpClient.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MedRecWebServicesPort", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(PrescriptionWS))]
    public class MedRecWebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public MedRecWebServices() {
            this.Url = "http://localhost:80/ws_medrec/MedRecWebServices";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
        public void registerPatient(PatientWS patient, string password) {
            this.Invoke("registerPatient", new object[] {
                        patient,
                        password});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginregisterPatient(PatientWS patient, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("registerPatient", new object[] {
                        patient,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndregisterPatient(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
        public void updatePatient(PatientWS patient) {
            this.Invoke("updatePatient", new object[] {
                        patient});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdatePatient(PatientWS patient, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updatePatient", new object[] {
                        patient}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdatePatient(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public PatientWS findPatientBySsn(string id) {
            object[] results = this.Invoke("findPatientBySsn", new object[] {
                        id});
            return ((PatientWS)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindPatientBySsn(string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findPatientBySsn", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public PatientWS EndfindPatientBySsn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PatientWS)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public PatientWS[] findPatientByLastNameWild(string lastName) {
            object[] results = this.Invoke("findPatientByLastNameWild", new object[] {
                        lastName});
            return ((PatientWS[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindPatientByLastNameWild(string lastName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findPatientByLastNameWild", new object[] {
                        lastName}, callback, asyncState);
        }
        
        /// <remarks/>
        public PatientWS[] EndfindPatientByLastNameWild(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PatientWS[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
        public void addRecord(RecordWS record) {
            this.Invoke("addRecord", new object[] {
                        record});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaddRecord(RecordWS record, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addRecord", new object[] {
                        record}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndaddRecord(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public RecordsSummaryWS getRecordsSummary(int id) {
            object[] results = this.Invoke("getRecordsSummary", new object[] {
                        id});
            return ((RecordsSummaryWS)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRecordsSummary(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRecordsSummary", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public RecordsSummaryWS EndgetRecordsSummary(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RecordsSummaryWS)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public RecordWS getRecord(int id) {
            object[] results = this.Invoke("getRecord", new object[] {
                        id});
            return ((RecordWS)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRecord(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRecord", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public RecordWS EndgetRecord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RecordWS)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("PatientWS", "java:com.bea.medrec.webservices")]
    public class PatientWS {
        
        /// <remarks/>
        public AddressWS addressWS;
        
        /// <remarks/>
        public string dateOfBirth;
        
        /// <remarks/>
        public string email;
        
        /// <remarks/>
        public string firstName;
        
        /// <remarks/>
        public string gender;
        
        /// <remarks/>
        public int id;
        
        /// <remarks/>
        public string lastName;
        
        /// <remarks/>
        public string middleName;
        
        /// <remarks/>
        public string phone;
        
        /// <remarks/>
        public string ssn;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("AddressWS", "java:com.bea.medrec.webservices")]
    public class AddressWS {
        
        /// <remarks/>
        public string city;
        
        /// <remarks/>
        public string country;
        
        /// <remarks/>
        public int id;
        
        /// <remarks/>
        public string state;
        
        /// <remarks/>
        public string streetName1;
        
        /// <remarks/>
        public string streetName2;
        
        /// <remarks/>
        public string zipCode;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RecordsSummaryWS", "java:com.bea.medrec.webservices")]
    public class RecordsSummaryWS {
        
        /// <remarks/>
        public PrescriptionWS[] prescriptions;
        
        /// <remarks/>
        public RecordWS[] records;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("PrescriptionWS", "java:com.bea.medrec.webservices")]
    public class PrescriptionWS {
        
        /// <remarks/>
        public string datePrescribed;
        
        /// <remarks/>
        public string dosage;
        
        /// <remarks/>
        public string drug;
        
        /// <remarks/>
        public string frequency;
        
        /// <remarks/>
        public int id;
        
        /// <remarks/>
        public string instructions;
        
        /// <remarks/>
        public int patientId;
        
        /// <remarks/>
        public int physicianId;
        
        /// <remarks/>
        public int recordId;
        
        /// <remarks/>
        public int refillsRemaining;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RecordWS", "java:com.bea.medrec.webservices")]
    public class RecordWS {
        
        /// <remarks/>
        public string date;
        
        /// <remarks/>
        public string diagnosis;
        
        /// <remarks/>
        public int id;
        
        /// <remarks/>
        public string notes;
        
        /// <remarks/>
        public int patientId;
        
        /// <remarks/>
        public int physicianId;
        
        /// <remarks/>
        public PrescriptionWS[] prescriptions;
        
        /// <remarks/>
        public string symptoms;
        
        /// <remarks/>
        public VitalSignsWS vitalSigns;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("VitalSignsWS", "java:com.bea.medrec.webservices")]
    public class VitalSignsWS {
        
        /// <remarks/>
        public string bloodPressure;
        
        /// <remarks/>
        public int height;
        
        /// <remarks/>
        public int id;
        
        /// <remarks/>
        public string pulse;
        
        /// <remarks/>
        public string temperature;
        
        /// <remarks/>
        public int weight;
    }
}
